GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impkb2UiLCJpZCI6IjYyNGI0MDhjY2ZhMjQ1M2I2Y2RlYjBhMSIsImlhdCI6MTY1MTc5NDA3OCwiZXhwIjoxNjUxNzk3Njc4fQ.FqkxqvJgp8usqRSRgvmrZ0xIdQh7mIlCmWZ5FWoendY

{
    "title": "Stampede",
    "author": "Machel Montano",
    "url": "test",
    "likes": 2,
    "user": "624b408ccfa2453b6cdeb0a1"
}

###
PUT http://localhost:3003/api/blogs/624c978d027ba881fb02552a
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impkb2UiLCJpZCI6IjYyNGI0MDhjY2ZhMjQ1M2I2Y2RlYjBhMSIsImlhdCI6MTY1MTc5NDA3OCwiZXhwIjoxNjUxNzk3Njc4fQ.FqkxqvJgp8usqRSRgvmrZ0xIdQh7mIlCmWZ5FWoendY

{
    "title": "Stampede",
    "author": "Machel Montano",
    "url": "test",
    "likes": 2,
    "user": "624b408ccfa2453b6cdeb0a1"
}

###
DELETE http://localhost:3003/api/blogs/624f35c501675242f07e8a90
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Impkb2UiLCJpZCI6IjYyNGI0MDhjY2ZhMjQ1M2I2Y2RlYjBhMSIsImlhdCI6MTY0OTM1ODI1MiwiZXhwIjoxNjQ5MzYxODUyfQ.p0YMCeCpF3VqiCxuh5DSRmnriPil0gnY_VvyD3KjVfg